---
all:
  children:
    managed:
      children:
        nvidia:
          hosts:
            H100-145:
            H100-149:
            H100-205:
        metax:
          hosts:
            mx-103:
            mx-104:
        mthreads:
          hosts:
            mthread-07:
            mthread-08:
        ascend:
          hosts:
            910C-120:
            910C-121:
        hygon:
          hosts: {}
        ppu:
          hosts:
            PPU-01:
            PPU-03:
            PPU-07:
            PPU-13:
